"""add subcategory is_periodic and due_day

Revision ID: fa33b7335fb1
Revises: 837ee5832ce5
Create Date: 2026-03-10 18:34:19.013523

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa33b7335fb1"
down_revision: str | None = "837ee5832ce5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subcategories",
        sa.Column("is_periodic", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("subcategories", sa.Column("due_day", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subcategories", "due_day")
    op.drop_column("subcategories", "is_periodic")
    # ### end Alembic commands ###
